-- POKE DDL MariaDB

DROP TABLE TB_AUTH;
DROP TABLE TB_BOARD;
DROP TABLE TB_USER;
DROP TABLE TB_PICK_POINT;
DROP TABLE TB_POKEMON_REF;

-- CREATE TABLE LIST
CREATE TABLE `TB_USER` (
	`USER_NO` INT(11) NOT NULL AUTO_INCREMENT,
	`USER_ID` VARCHAR(50) NOT NULL,
	`USER_NAME` VARCHAR(50) NOT NULL,
	`PASSWORD` VARCHAR(300) NOT NULL,
	`REG_DATE` DATETIME NOT NULL DEFAULT NOW(),
	`STATUS` VARCHAR(1) NOT NULL DEFAULT 'T',
	PRIMARY KEY(`USER_NO`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;


CREATE TABLE `TB_AUTH` (
	`IDX` INT(11) NOT NULL AUTO_INCREMENT,
	`USER_NO` INT(11) NOT NULL,
	`AUTH_CODE` VARCHAR(50) NOT NULL,
	`REG_DATE` DATETIME NOT NULL DEFAULT NOW(),
	PRIMARY KEY(`IDX`),
	CONSTRAINT `FK_AUTH_USER` FOREIGN KEY(`USER_NO`) REFERENCES TB_USER(`USER_NO`) ON DELETE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;


CREATE TABLE `TB_BOARD` (
	`BOARD_NO` INT(11) NOT NULL AUTO_INCREMENT,
	`USER_NO` INT(11) NOT NULL,
	`TITLE` VARCHAR(200) NOT NULL,
	`CONTENTS` MEDIUMTEXT NOT NULL,
	`ATTACHMENT_CNT` INT NOT NULL,
	`WRITE_DATE` DATETIME NOT NULL DEFAULT NOW(),
	`STATUS` VARCHAR(1) NOT NULL DEFAULT 'T',
	PRIMARY KEY(`BOARD_NO`),
	CONSTRAINT `FK_BOARD_USER` FOREIGN KEY(`USER_NO`) REFERENCES TB_USER(`USER_NO`) ON DELETE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;


CREATE TABLE `TB_PICK_POINT` (
	`IDX` INT(11) NOT NULL AUTO_INCREMENT,
	`CODE` VARCHAR(20) NOT NULL,
	`RARE` CHAR(2) NOT NULL,
	`RARITY` INT NOT NULL,
	PRIMARY KEY(`IDX`),
	CONSTRAINT CK_PICK_POINT_RARITY CHECK(RARITY > 0)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;


CREATE TABLE `TB_SUDOKU` (
	`IDX` INT(11) NOT NULL AUTO_INCREMENT,
	`SUDOKU` CHAR(81) NOT NULL,
	`LEVEL` INT NOT NULL DEFAULT 1,
	`REG_DATE` DATETIME NOT NULL DEFAULT NOW(),
	PRIMARY KEY(`IDX`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;













CREATE TABLE `TB_POKEMON` (
	`MON_ID` VARCHAR(50) NOT NULL,
	`MON_NO` VARCHAR(50) NOT NULL,
	`MON_NAME` VARCHAR(50) NOT NULL,
	`TYPE_A` VARCHAR(50) NOT NULL,
	`TYPE_B` VARCHAR(50),
	`MON_OPT` VARCHAR(50),
	PRIMARY KEY(`MON_ID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;


CREATE TABLE `TB_POKEMON_REF` (
	`MON_ID` VARCHAR(50) NOT NULL,
	`BEFORE_ID` VARCHAR(50),
	`BEFORE_STEP` INT,
	`RARE` CHAR(2) NOT NULL,
	`REQ_STEP` VARCHAR(50),
	PRIMARY KEY(`MON_ID`),
	CONSTRAINT `FK_TB_POKEMON_REF_ID` FOREIGN KEY(`MON_ID`) REFERENCES TB_POKEMON(`MON_ID`) ON DELETE CASCADE,
	CONSTRAINT `FK_TB_POKEMON_REF_BE` FOREIGN KEY(`BEFORE_ID`) REFERENCES TB_POKEMON(`MON_ID`) ON DELETE SET NULL
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;







