-- POKE DDL MariaDB

-- DROP TABLE TB_AUTH;
-- DROP TABLE TB_USER;


-- CREATE TABLE LIST
CREATE TABLE `TB_USER`(
	`USER_NO` INT(11) NOT NULL AUTO_INCREMENT,
	`USER_ID` VARCHAR(50) NOT NULL,
	`USER_NAME` VARCHAR(50) NOT NULL,
	`PASSWORD` VARCHAR(300) NOT NULL,
	`REG_DATE` DATETIME NOT NULL DEFAULT NOW(),
	`STATUS` VARCHAR(1) NOT NULL DEFAULT 'T',
	PRIMARY KEY(`USER_NO`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;


CREATE TABLE `TB_AUTH`(
	`IDX` INT(11) NOT NULL AUTO_INCREMENT,
	`USER_NO` INT(11) NOT NULL,
	`AUTH_CODE` VARCHAR(50) NOT NULL,
	`REG_DATE` DATETIME NOT NULL DEFAULT NOW(),
	PRIMARY KEY(`IDX`),
	CONSTRAINT `FK_AUTH_USER` FOREIGN KEY(`USER_NO`) REFERENCES TB_USER(`USER_NO`) ON DELETE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;


CREATE TABLE `TB_BOARD`(
	`BOARD_NO` INT(11) NOT NULL AUTO_INCREMENT,
	`USER_NO` INT(11) NOT NULL,
	`TITLE` VARCHAR(200) NOT NULL,
	`CONTENTS` MEDIUMTEXT NOT NULL,
	`ATTACHMENT_CNT` INT NOT NULL,
	`WRITE_DATE` DATETIME NOT NULL DEFAULT NOW(),
	`STATUS` VARCHAR(1) NOT NULL DEFAULT 'T',
	PRIMARY KEY(`BOARD_NO`),
	CONSTRAINT `FK_BOARD_USER` FOREIGN KEY(`USER_NO`) REFERENCES TB_USER(`USER_NO`) ON DELETE CASCADE
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;


CREATE TABLE `TB_POKEMON`(
	`MON_ID` VARCHAR(50) NOT NULL,
	`MON_NO` VARCHAR(50) NOT NULL,
	`MON_NAME` VARCHAR(50) NOT NULL,
	`TYPE_A` VARCHAR(50) NOT NULL,
	`TYPE_B` VARCHAR(50),
	`MON_OPT` VARCHAR(50),
	PRIMARY KEY(`MON_ID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;










